import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Welcome to Wanderwall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Welcome!</h1>
        <p>
          WanderWall is a catalouge of reviews for different
          rock climbing gyms that I have traveled to.
          There is also a list of places that I have traveled to on the travel tab.
          The About me tab contains a list of my credentials and other information about me.
        </p>
      </div>
    </div>
  );
}
