import Head from 'next/head';

export default function Travel() {
  return (
    <div>
      <Head>
        <title>WanderWall - Travel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        Travel
      </div>
    </div>
  );
}
