import Head from 'next/head';
import Chart from 'react-google-charts';
import styled from 'styled-components';

const data = [
  ['Country', 'value'],
  ['US', 2000],
  ['MX', 2018],
  ['IS', 2020],
  ['CR', 2021],
  ['GB', 2021],
  ['CA', 2022],
  ['CH', 2022],
  ['IT', 2022],
  ['VA', 2022],
  ['AT', 2022],
  ['DE', 2022],
  ['NL', 2022],
  ['BE', 2022],
  ['FR', 2022],
  ['DK', 2022],
  ['NO', 2023],
  ['SE', 2023],
  ['FI', 2023],
];

const options = {
  colorAxis: {
    colors: ['#1b2124', '#3e799b', '#578fcc', '#54c1ae', '#45e281', '#bde75b', '#f7ae4e'],
    values: [2000, 2018, 2019, 2020, 2021, 2022, 2023],
  },
  legend: 'none',
  tooltip: {
    trigger: 'none',
  },
};

const HeaderContainer = styled.div`
  padding: 24px 0;
  text-align: center;
`;

const ChartContainer = styled.div`
  margin: 15px 0;
  padding: 15px;
  border: solid 1px black;
`;

export default function Travel() {
  return (
    <div>
      <Head>
        <title>WanderWall - Travel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <HeaderContainer>
          <h1>Travels</h1>
        </HeaderContainer>
        <p>The Color represents the year of the first time that I visited that country.</p>
        <ChartContainer>
          <Chart chartType="GeoChart" width="100%" height="700px" data={data} options={options} />
        </ChartContainer>
      </div>
    </div>
  );
}
